import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import MainMenu from "@/components/mainMenu";
import { getUser } from "@/lib/auth/getUser";
import { getProfile } from "@/lib/auth/getProfile";
import { getAccounts } from "@/app/accounts/actions";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await getUser();
  const profile = user ? await getProfile(user.id) : null;
  const accounts = user ? await getAccounts() : null;

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {user ?
          <MainMenu user={profile} accounts={accounts} />
        : null
        }
        {children}
      </body>
    </html>
  );
}
